export const loginScreenStyles = {
  shell: "flex min-h-screen items-center justify-center",
  grid: "grid w-full max-w-6xl gap-8 lg:grid-cols-[1.15fr_0.85fr]",
  heroCard: "glass-panel relative overflow-hidden rounded-[var(--radius-card-xl)] p-8 sm:p-10 lg:p-12",
  heroGlow: "brand-hero-glow absolute inset-x-0 top-0 h-32",
  heroContent: "relative max-w-2xl space-y-8",
  heroBadge: "brand-surface-primary inline-flex rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-[0.24em] text-white",
  heroTextGroup: "space-y-4",
  heroTitle: "max-w-xl text-4xl font-semibold tracking-[-0.06em] text-white sm:text-6xl",
  heroSubtitle: "max-w-xl text-base leading-7 text-slate-300 sm:text-lg",
  heroBullets: "grid gap-4 sm:grid-cols-3",
  heroBullet: "rounded-3xl border border-white/10 bg-slate-950/40 p-4 text-sm leading-6 text-slate-300",
  formCard: "glass-panel rounded-[var(--radius-card-xl)] p-8 sm:p-10",
  formHeader: "space-y-3",
  overline: "text-sm uppercase tracking-[0.24em] text-slate-200",
  formTitle: "text-3xl font-semibold tracking-[-0.04em] text-white",
  formDescription: "text-sm leading-6 text-slate-300",
  errorWord: "status-error-text font-semibold",
  scenarioBadge: "brand-surface-primary inline-flex rounded-full px-3 py-1 text-xs font-medium text-white",
  form: "mt-8 space-y-5",
  fieldGroup: "space-y-2",
  label: "text-sm font-medium text-slate-200",
  fieldError: "status-error-text text-sm",
  mutationError: "status-error-surface status-error-text-strong rounded-2xl px-4 py-3 text-sm",
  submit: "primary-button w-full",
  submitPending: "flex items-center gap-3",
} as const;
