export const transferScreenStyles = {
  layout: "grid gap-6 lg:grid-cols-[1.12fr_0.88fr]",
  panel: "glass-panel rounded-[var(--radius-card-xl)] p-6 sm:p-8",
  sectionTitle: "mt-3 text-3xl font-semibold tracking-[-0.05em] text-white",
  overline: "text-sm uppercase tracking-[0.24em] text-slate-200",
  scenarioPill: "brand-surface-primary mt-4 inline-flex rounded-full px-3 py-1 text-xs font-medium text-white",
  form: "mt-8 space-y-6",
  fieldGroup: "space-y-2",
  label: "text-sm font-medium text-slate-200",
  fieldError: "status-error-text text-sm",
  recipientSection: "space-y-4",
  recipientTypeButtons: "flex flex-wrap gap-3",
  contactsList: "space-y-3",
  contactLoading: "flex items-center gap-3 rounded-3xl border border-white/10 bg-slate-950/35 p-4 text-slate-300",
  contactRow: "brand-hover-border-primary flex cursor-pointer items-start gap-3 rounded-3xl border border-white/10 bg-slate-950/35 p-4 transition",
  contactBankAlias: "mt-1 text-xs uppercase tracking-[0.22em] text-slate-300",
  manualGrid: "grid gap-4 md:grid-cols-2",
  checkboxCard: "flex items-center gap-3 rounded-3xl border border-white/10 bg-slate-950/35 px-4 py-3 text-sm text-slate-200",
  ruleMessage: "status-warning-surface status-warning-text rounded-2xl px-4 py-3 text-sm",
  actions: "flex flex-col gap-3 sm:flex-row sm:justify-end",
  reviewCard: "rounded-[var(--radius-card-lg)] border border-white/10 bg-slate-950/40 p-6",
  reviewGrid: "mt-6 grid gap-6 sm:grid-cols-2",
  reviewValue: "mt-2 text-3xl font-semibold text-white",
  reviewRecipientCard: "mt-6 rounded-3xl border border-white/10 bg-slate-900/60 p-5",
  reviewRecipientName: "mt-2 text-lg font-semibold text-white",
  reviewRecipientReference: "mt-1 text-sm text-slate-300",
  reviewRecipientAlias: "mt-3 text-xs uppercase tracking-[0.22em] text-slate-300",
  scenarioHintCard: "brand-surface-primary-strong rounded-[var(--radius-card-lg)] p-5 text-sm leading-6 text-white",
  confirmPendingText: "flex items-center gap-3",
  aside: "space-y-6",
  asideCard: "glass-panel rounded-[var(--radius-card-xl)] p-6",
  asideTitle: "mt-3 text-2xl font-semibold text-white",
  asideSubtitle: "mt-2 text-sm text-slate-300",
  balanceTitle: "mt-3 text-4xl font-semibold tracking-[-0.05em] text-white",
  balanceHint: "mt-3 text-sm leading-6 text-slate-300",
  activityTitle: "text-lg font-semibold text-white",
  qaDescription: "mt-2 text-sm leading-6 text-slate-300",
  qaToggle: "mt-4 flex items-center justify-between rounded-2xl border border-white/10 bg-slate-950/35 px-4 py-3",
  qaToggleLabel: "text-sm font-medium text-white",
  qaToggleHint: "text-xs text-slate-200",
  qaToggleOn: "primary-button !px-3 !py-2",
  qaToggleOff: "secondary-button !px-3 !py-2",
  qaSelectGroup: "mt-4 space-y-2",
  qaNote: "text-xs text-slate-200",
} as const;

export const transferResultStyles = {
  container: "mx-auto max-w-3xl",
  card: "glass-panel rounded-[36px] p-8 text-center sm:p-10",
  successIcon: "status-success-surface mx-auto flex h-20 w-20 items-center justify-center rounded-full text-4xl text-white",
  errorIcon: "status-error-surface status-error-text mx-auto flex h-20 w-20 items-center justify-center rounded-full text-4xl",
  successOverline: "mt-6 text-sm uppercase tracking-[0.24em] text-white",
  errorOverline: "status-error-text-strong mt-6 text-sm uppercase tracking-[0.24em]",
  title: "mt-3 text-4xl font-semibold tracking-[-0.05em] text-white sm:text-5xl",
  description: "mt-4 text-base leading-7 text-slate-300",
  hint: "mt-3 text-sm leading-6 text-slate-200",
  detailCard: "mt-8 rounded-[var(--radius-card-lg)] border border-white/10 bg-slate-950/40 p-6 text-left",
  detailGrid: "grid gap-5 sm:grid-cols-2",
  detailLabel: "text-sm text-slate-200",
  detailValue: "mt-2 font-semibold text-white",
  detailSubValue: "mt-1 text-sm text-slate-300",
  actions: "mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center",
} as const;
