export const accountBalanceCardStyles = {
  card: "glass-panel relative overflow-hidden rounded-[var(--radius-card-xl)] p-6 sm:p-8",
  glow: "brand-glow-primary absolute right-0 top-0 h-28 w-28 rounded-full blur-3xl",
  content: "relative",
  title: "text-sm uppercase tracking-[0.26em] text-slate-200",
  amount: "mt-4 text-4xl font-semibold tracking-[-0.06em] text-white sm:text-5xl",
  amountCurrency: "ml-2 text-sm uppercase tracking-[0.22em] text-slate-200 align-middle",
} as const;

export const walletHeaderStyles = {
  container: "glass-panel mb-6 flex flex-col gap-4 rounded-[var(--radius-card-lg)] px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6",
  brand: "text-xs uppercase tracking-[0.24em] text-white/80",
  name: "mt-1 text-xl font-semibold text-white",
  actions: "flex flex-col gap-3 sm:flex-row sm:items-center",
  nav: "flex items-center gap-2 rounded-full border border-white/10 bg-slate-950/30 p-1",
  navLinkBase: "rounded-full px-4 py-2 text-sm font-medium transition",
  navLinkActive: "brand-gradient text-white",
  navLinkIdle: "text-slate-300 brand-hover-bg-white hover:text-white",
  pendingText: "flex items-center gap-2",
} as const;

export const transactionsListStyles = {
  loadingCard: "glass-panel rounded-[var(--radius-card-lg)] p-8",
  loadingText: "flex items-center gap-3 text-slate-300",
  card: "glass-panel rounded-[var(--radius-card-lg)] p-4 sm:p-5",
  header: "flex items-center justify-between px-2 pb-3 pt-1",
  title: "text-lg font-semibold text-white",
  subtitle: "text-sm text-slate-200",
  summary: "mt-1 text-xs uppercase tracking-[0.22em] text-slate-300",
  list: "space-y-3",
  item: "brand-hover-border-primary rounded-3xl border border-white/10 bg-slate-950/35 p-4 transition",
  itemRow: "flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
  recipientRow: "flex items-center gap-2",
  recipientName: "font-medium text-white",
  itemDescription: "mt-2 text-sm text-slate-200",
  itemAccountNumber: "mt-1 text-xs text-slate-200",
  itemReference: "mt-1 text-xs uppercase tracking-[0.22em] text-slate-300",
  itemMetaRow: "mt-3 flex items-center justify-between gap-3",
  detailLink: "brand-text-accent text-sm font-medium",
  amountBlock: "text-left sm:text-right",
  amountText: "text-lg font-semibold text-white",
  amountCurrency: "ml-1 text-xs uppercase tracking-[0.22em] text-slate-200",
  dateText: "mt-1 text-sm text-slate-200",
  loadMoreRow: "mt-5 flex justify-center px-2 pb-1",
  pendingButtonText: "flex items-center gap-2",
} as const;

export const transactionDetailStyles = {
  container: "mx-auto w-full max-w-4xl space-y-6",
  loadingCard: "glass-panel rounded-[var(--radius-card-lg)] p-8",
  loadingText: "flex items-center gap-3 text-slate-300",
  card: "glass-panel rounded-[var(--radius-card-xl)] p-6 sm:p-8",
  topRow: "flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between",
  overline: "text-sm uppercase tracking-[0.24em] text-slate-200",
  title: "mt-2 text-3xl font-semibold tracking-[-0.05em] text-white",
  amount: "mt-6 text-4xl font-semibold tracking-[-0.06em] text-white",
  amountCurrency: "ml-2 text-sm uppercase tracking-[0.24em] text-slate-200",
  grid: "mt-8 grid gap-4 md:grid-cols-2",
  item: "rounded-3xl border border-white/10 bg-slate-950/35 p-4",
  label: "text-xs uppercase tracking-[0.2em] text-slate-300",
  value: "mt-2 text-sm text-slate-100",
  actions: "mt-8 flex flex-wrap gap-3",
  actionSecondary: "secondary-button",
  actionPrimary: "primary-button",
} as const;

export const homeScreenStyles = {
  grid: "grid gap-6 lg:grid-cols-[1.15fr_0.85fr]",
  mainColumn: "space-y-6",
  loadingBalanceCard: "glass-panel flex min-h-[220px] items-center justify-center rounded-[var(--radius-card-xl)]",
  loadingBalanceText: "flex items-center gap-3 text-slate-300",
  aside: "space-y-6",
  profileCard: "glass-panel rounded-[var(--radius-card-xl)] p-6",
  overline: "text-sm uppercase tracking-[0.24em] text-slate-200",
  profileName: "mt-4 text-2xl font-semibold tracking-[-0.04em] text-white",
  profileDescription: "mt-3 text-sm leading-6 text-slate-300",
  profileGrid: "mt-6 grid gap-3 sm:grid-cols-2",
  profileItem: "rounded-3xl border border-white/10 bg-slate-950/35 p-4",
  profileItemLabel: "text-xs uppercase tracking-[0.22em] text-slate-300",
  profileItemValue: "mt-2 text-lg font-semibold text-white",
  architectureCard: "glass-panel rounded-[var(--radius-card-xl)] p-6",
  architectureTitle: "text-lg font-semibold text-white",
  architectureList: "mt-4 space-y-3 text-sm leading-6 text-slate-300",
} as const;
